#!/system/bin/sh
# ZeetaaTweak V0.3.1
# by @NotZeetaa

# Log path
LOG_FILE="/data/data/com.zeetaa.zeetaatweaks/files/log/main_log"

if [ -e $LOG_FILE ]; then
  rm -rf $LOG_FILE
fi

sendToLog() {
  timeZone=$(getprop persist.sys.timezone)
  printDate=$(TZ="$timeZone" date +"%H:%M:%S:%3N %d-%m-%Y")

  echo "[$printDate] $1" >>"$LOG_FILE"
}

write() {
  #chmod 0644 "$1"
  echo "$2" >"$1"

  currentValue=$(cat "$1")

  if [ "$currentValue" -eq "$2" ]; then
    sendToLog "$2 -✅-> $1"
  else
    sendToLog "$2 -❌-> $1"
  fi

  unset currentValue
}


write /sys/devices/system/cpu/cpu0/cpufreq/schedutil/down_rate_limit_us "0"
write /sys/devices/system/cpu/cpu1/cpufreq/schedutil/down_rate_limit_us "0"
write /sys/devices/system/cpu/cpu2/cpufreq/schedutil/down_rate_limit_us "0"
write /sys/devices/system/cpu/cpu3/cpufreq/schedutil/down_rate_limit_us "0"
write /sys/devices/system/cpu/cpu4/cpufreq/schedutil/down_rate_limit_us "0"
write /sys/devices/system/cpu/cpu5/cpufreq/schedutil/down_rate_limit_us "0"
write /sys/devices/system/cpu/cpu6/cpufreq/schedutil/down_rate_limit_us "0"
write /sys/devices/system/cpu/cpu7/cpufreq/schedutil/down_rate_limit_us "0"

write /sys/devices/system/cpu/cpu0/cpufreq/schedutil/up_rate_limit_us "0"
write /sys/devices/system/cpu/cpu1/cpufreq/schedutil/up_rate_limit_us "0"
write /sys/devices/system/cpu/cpu2/cpufreq/schedutil/up_rate_limit_us "0"
write /sys/devices/system/cpu/cpu3/cpufreq/schedutil/up_rate_limit_us "0"
write /sys/devices/system/cpu/cpu4/cpufreq/schedutil/up_rate_limit_us "0"
write /sys/devices/system/cpu/cpu5/cpufreq/schedutil/up_rate_limit_us "0"
write /sys/devices/system/cpu/cpu6/cpufreq/schedutil/up_rate_limit_us "0"
write /sys/devices/system/cpu/cpu7/cpufreq/schedutil/up_rate_limit_us "0"
write /sys/devices/system/cpu/cpu0/cpufreq/schedutil/iowait_boost_enable "0"
write /sys/devices/system/cpu/cpu1/cpufreq/schedutil/iowait_boost_enable "0"
write /sys/devices/system/cpu/cpu2/cpufreq/schedutil/iowait_boost_enable "0"
write /sys/devices/system/cpu/cpu3/cpufreq/schedutil/iowait_boost_enable "0"
write /sys/devices/system/cpu/cpu4/cpufreq/schedutil/iowait_boost_enable "0"
write /sys/devices/system/cpu/cpu5/cpufreq/schedutil/iowait_boost_enable "0"
write /sys/devices/system/cpu/cpu6/cpufreq/schedutil/iowait_boost_enable "0"
write /sys/devices/system/cpu/cpu7/cpufreq/schedutil/iowait_boost_enable "0"
write /sys/devices/system/cpu/cpu0/cpufreq/interactive/timer_slack "8"
write /sys/devices/system/cpu/cpu1/cpufreq/interactive/timer_slack "8"
write /sys/devices/system/cpu/cpu2/cpufreq/interactive/timer_slack "8"
write /sys/devices/system/cpu/cpu3/cpufreq/interactive/timer_slack "8"
write /sys/devices/system/cpu/cpu4/cpufreq/interactive/timer_slack "8"
write /sys/devices/system/cpu/cpu5/cpufreq/interactive/timer_slack "8"
write /sys/devices/system/cpu/cpu6/cpufreq/interactive/timer_slack "8"
write /sys/devices/system/cpu/cpu7/cpufreq/interactive/timer_slack "8"

# Better Battery Efficient
write /sys/module/workqueue/parameters/power_efficient "Y"

# Adreno Idler
write /sys/module/adreno_idler/paremeters/adreno_idler_active "Y"

# Gpu Tweaks
write /sys/class/kgsl/kgsl-3d0/throttling "1"
write /sys/class/kgsl/kgsl-3d0/default_pwrlevel "5"
write /sys/class/kgsl/kgsl-3d0/bus_split "1"

# Scheduler
write /sys/block/sda/queue/scheduler "cfq"
write /sys/block/sdb/queue/scheduler "cfq"
write /sys/block/sdc/queue/scheduler "cfq"
write /sys/block/sdd/queue/scheduler "cfq"
write /sys/block/sde/queue/scheduler "cfq"
write /sys/block/sdf/queue/scheduler "cfq"
write /sys/block/sda/queue/rq_affinity "0"
write /sys/block/sda/queue/iostats "0"
write /sys/block/sda/queue/read_ahead_kb "64"
write /sys/block/sdb/queue/rq_affinity "0"
write /sys/block/sdb/queue/iostats "0"
write /sys/block/sdb/queue/read_ahead_kb "64"
write /sys/block/sdc/queue/rq_affinity "0"
write /sys/block/sdc/queue/iostats "0"
write /sys/block/sdc/queue/read_ahead_kb "64"
write /sys/block/sdd/queue/rq_affinity "0"
write /sys/block/sdd/queue/iostats "0"
write /sys/block/sdd/queue/read_ahead_kb "64"
write /sys/block/sde/queue/rq_affinity "0"
write /sys/block/sde/queue/iostats "0"
write /sys/block/sde/queue/read_ahead_kb "64"
write /sys/block/sdf/queue/rq_affinity "0"
write /sys/block/sdf/queue/iostats "0"
write /sys/block/sdf/queue/read_ahead_kb "64"
write /sys/block/mmcblk0/queue/read_ahead_kb "64"
write /sys/block/mmcblk0/queue/iostats "0"
write /sys/block/mmcblk0/queue/rq_affinity "0"
write /sys/block/mmcblk1/queue/read_ahead_kb "64"
write /sys/block/mmcblk1/queue/iostats "0"
write /sys/block/mmcblk1/queue/rq_affinity "0"

# Tweaked Cfq Recommended by Red hat
# Edited by @NotZeetaa
write /sys/block/sda/queue/iosched/low_latency "1"
write /sys/block/sdb/queue/iosched/low_latency "1"
write /sys/block/sdc/queue/iosched/low_latency "1"
write /sys/block/sdd/queue/iosched/low_latency "1"
write /sys/block/sde/queue/iosched/low_latency "1"
write /sys/block/sdf/queue/iosched/low_latency "1"
write /sys/block/sda/queue/iosched/quantum "4"
write /sys/block/sda/queue/iosched/group_idle "1"
write /sys/block/sda/queue/iosched/slice_idle "0"
write /sys/block/sdb/queue/iosched/quantum "4"
write /sys/block/sdb/queue/iosched/group_idle "1"
write /sys/block/sdb/queue/iosched/slice_idle "0"
write /sys/block/sdc/queue/iosched/quantum "4"
write /sys/block/sdc/queue/iosched/group_idle "1"
write /sys/block/sdc/queue/iosched/slice_idle "0"
write /sys/block/sde/queue/iosched/quantum "4"
write /sys/block/sde/queue/iosched/group_idle "1"
write /sys/block/sde/queue/iosched/slice_idle "0"
write /sys/block/sdf/queue/iosched/quantum "4"
write /sys/block/sdf/queue/iosched/group_idle "1"
write /sys/block/sdf/queue/iosched/slice_idle "0"

# Cpu Sets Tweak
write /dev/cpuset/camera-daemon/cpus "0-4"
write /dev/cpuset/restricted/cpus "0-6"
write /dev/cpuset/foreground/cpus "0-4"
write /dev/cpuset/top-app/cpus "0-7"
write /dev/cpuset/system-background/cpus "0-1"
write /dev/cpuset/background/cpus "0"

# Dev Stune Boost
# Fast Sensivity in Game
write /dev/stune/background/schedtune.boost "0"
write /dev/stune/foreground/schedtune.boost "0"
write /dev/stune/rt/schedtune.boost "0"
write /dev/stune/top-app/schedtune.boost "0"
write /dev/stune/schedtune.boost "0"
write /dev/stune/top-app/schedtune.prefer_idle "1"

# Fs
write /proc/sys/fs/lease-break-time "80"
write /proc/sys/fs/dir-notify-enable "1"
write /proc/sys/kernel/sched_migration_cost_ns "300000"
write /proc/sys/kernel/perf_cpu_time_max_percent "95"
write /proc/sys/kernel/sched_min_task_util_for_colocation "1000"
write /proc/sys/kernel/sched_min_task_util_for_boost "1000"
write /proc/sys/kernel/sched_min_granularity_ns "1500000"
write /proc/sys/kernel/sched_wakeup_granularity_ns "1500000"
write /proc/sys/kernel/sched_rt_runtime_us "750000"
write /proc/sys/kernel/sched_child_runs_first "0"
write /proc/sys/kernel/timer_migration "1"
write /proc/sys/kernel/sched_boost_top_app "0"
write /proc/sys/kernel/sched_walt_rotate_big_tasks "0"
write /proc/sys/kernel/sched_boost "0"
write /proc/sys/kernel/sched_nr_migrate "2"
write /proc/sys/kernel/sched_schedstats "0"
write /proc/sys/net/ipv4/tcp_fastopen 3
write /proc/sys/vm/page-cluster 0
write /proc/sys/net/ipv4/tcp_timestamps "1"

# Lpm Levels
Tweak
write /sys/module/lpm_levels/L3/cpu0/rail-pc/idle_enabled "Y"
write /sys/module/lpm_levels/L3/cpu1/rail-pc/idle_enabled "Y"
write /sys/module/lpm_levels/L3/cpu2/rail-pc/idle_enabled "Y"
write /sys/module/lpm_levels/L3/cpu3/rail-pc/idle_enabled "Y"
write /sys/module/lpm_levels/L3/cpu4/rail-pc/idle_enabled "Y"
write /sys/module/lpm_levels/L3/cpu5/rail-pc/idle_enabled "Y"
write /sys/module/lpm_levels/L3/cpu6/rail-pc/idle_enabled "Y"
write /sys/module/lpm_levels/L3/cpu7/rail-pc/idle_enabled "Y"
write /sys/module/lpm_levels/L3/l3-wfi/idle_enabled "Y"
write /sys/module/lpm_levels/L3/llcc-off "Y"

# Lpm Levels Tweak V2 
# All Credits to Beast Mode ( @beast_project )
write /sys/module/lpm_levels/system/pwr/cpu0/ret/idle_enabled "Y"
write /sys/module/lpm_levels/system/pwr/cpu1/ret/idle_enabled "Y"
write /sys/module/lpm_levels/system/pwr/cpu2/ret/idle_enabled "Y"
write /sys/module/lpm_levels/system/pwr/cpu3/ret/idle_enabled "Y"
write /sys/module/lpm_levels/system/perf/cpu4/ret/idle_enabled
"Y"
write /sys/module/lpm_levels/system/perf/cpu5/ret/idle_enabled "Y"
write /sys/module/lpm_levels/system/perf/cpu6/ret/idle_enabled "Y"
write /sys/module/lpm_levels/system/perf/cpu7/ret/idle_enabled "Y"
write /sys/module/lpm_levels/system/pwr/pwr-l2-dynret/idle_enabled "Y"
write /sys/module/lpm_levels/system/perf/perf-l2-dynret/idle_enabled "Y"
write /sys/module/lpm_levels/system/pwr/pwr-l2-ret/idle_enabled "Y"
write /sys/module/lpm_levels/system/perf/perf-l2-ret/idle_enabled "Y"
write /sys/module/lpm_levels/parameters/sleep_disabled "N"

# Boost Control Tweak
# Credits to @Ratoriku
write /sys/module/boost_control/parameters/app_launch_boost_ms
"0"

# Scheduler features
write /sys/kernel/debug/sched_features "NO_NEXT_BUDDY"
write /sys/kernel/debug/sched_features "NO_TTWU_QUEUE"
write /sys/kernel/debug/sched_features "WAKEUP_PREEMPTION"
write /sys/kernel/debug/sched_features "GENTLE_FAIR_SLEEPERS"
write /sys/kernel/debug/sched_features "NO_STUNE_BOOST_BIAS_BIG"
write /sys/kernel/debug/sched_features "NO_CACHE_HOT_BUDDY"