#!/system/bin/sh
# ZeetaaTweak V1
# Log path
LOG_FILE="/data/data/com.zeetaa.zeetaatweaks/files/log/main_log"

if [ -e $LOG_FILE ]; then
  rm -rf $LOG_FILE
fi

sendToLog() {
  timeZone=$(getprop persist.sys.timezone)
  printDate=$(TZ="$timeZone" date +"%H:%M:%S:%3N %d-%m-%Y")

  echo "[$printDate] $1" >>"$LOG_FILE"
}

write() {
  #chmod 0644 "$1"
  echo "$2" >"$1"

  currentValue=$(cat "$1")

  if [ "$currentValue" -eq "$2" ]; then
    sendToLog "$2 -✅-> $1"
  else
    sendToLog "$2 -⚠️-> $1"
  fi

  unset currentValue
}


write /sys/devices/system/cpu/cpu0/cpufreq/schedutil/down_rate_limit_us "0"
write /sys/devices/system/cpu/cpu1/cpufreq/schedutil/down_rate_limit_us "0"
write /sys/devices/system/cpu/cpu2/cpufreq/schedutil/down_rate_limit_us "0"
write /sys/devices/system/cpu/cpu3/cpufreq/schedutil/down_rate_limit_us "0"
write /sys/devices/system/cpu/cpu4/cpufreq/schedutil/down_rate_limit_us "0"
write /sys/devices/system/cpu/cpu5/cpufreq/schedutil/down_rate_limit_us "0"
write /sys/devices/system/cpu/cpu6/cpufreq/schedutil/down_rate_limit_us "0"
write /sys/devices/system/cpu/cpu7/cpufreq/schedutil/down_rate_limit_us "0"

write /sys/devices/system/cpu/cpu0/cpufreq/schedutil/up_rate_limit_us "0"
write /sys/devices/system/cpu/cpu1/cpufreq/schedutil/up_rate_limit_us "0"
write /sys/devices/system/cpu/cpu2/cpufreq/schedutil/up_rate_limit_us "0"
write /sys/devices/system/cpu/cpu3/cpufreq/schedutil/up_rate_limit_us "0"
write /sys/devices/system/cpu/cpu4/cpufreq/schedutil/up_rate_limit_us "0"
write /sys/devices/system/cpu/cpu5/cpufreq/schedutil/up_rate_limit_us "0"
write /sys/devices/system/cpu/cpu6/cpufreq/schedutil/up_rate_limit_us "0"
write /sys/devices/system/cpu/cpu7/cpufreq/schedutil/up_rate_limit_us "0"
write /sys/devices/system/cpu/cpu0/cpufreq/schedutil/iowait_boost_enable "1"
write /sys/devices/system/cpu/cpu1/cpufreq/schedutil/iowait_boost_enable "1"
write /sys/devices/system/cpu/cpu2/cpufreq/schedutil/iowait_boost_enable "1"
write /sys/devices/system/cpu/cpu3/cpufreq/schedutil/iowait_boost_enable "1"
write /sys/devices/system/cpu/cpu4/cpufreq/schedutil/iowait_boost_enable "1"
write /sys/devices/system/cpu/cpu5/cpufreq/schedutil/iowait_boost_enable "1"
write /sys/devices/system/cpu/cpu6/cpufreq/schedutil/iowait_boost_enable "1"
write /sys/devices/system/cpu/cpu7/cpufreq/schedutil/iowait_boost_enable "1"
write /sys/devices/system/cpu/cpu0/cpufreq/interactive/timer_slack "-1"
write /sys/devices/system/cpu/cpu1/cpufreq/interactive/timer_slack "-1"
write /sys/devices/system/cpu/cpu2/cpufreq/interactive/timer_slack "-1"
write /sys/devices/system/cpu/cpu3/cpufreq/interactive/timer_slack "-1"
write /sys/devices/system/cpu/cpu4/cpufreq/interactive/timer_slack "-1"
write /sys/devices/system/cpu/cpu5/cpufreq/interactive/timer_slack "-1"
write /sys/devices/system/cpu/cpu6/cpufreq/interactive/timer_slack "-1"
write /sys/devices/system/cpu/cpu7/cpufreq/interactive/timer_slack "-1"

for pro in /sys/devices/system/cpu/cpu*/cpufreq/interactive_pro/
do
    write "$pro/timer_slack" "-1"
done

# Power Efficient tweak
write /sys/module/workqueue/parameters/power_efficient "Y"

# Adreno Idler
write /sys/module/adreno_idler/paremeters/adreno_idler_active "N"

# Gpu Tweaks
write /sys/class/kgsl/kgsl-3d0/throttling "0"
write /sys/class/kgsl/kgsl-3d0/default_pwrlevel "2"
write /sys/class/kgsl/kgsl-3d0/bus_split "0"

# Scheduler tweak

for sched in /sys/block/*/queue
do
    write "$sched/scheduler" "cfq"
    write "$sched/rq_affinity" "2"
    write "$sched/iostats" "0"
    write "$sched/read_ahead_kb" "128"
done

# Tweaked Cfq Recommended by Red hat
# Edited by @NotZeetaa

for iosched in /sys/block/*/queue/iosched
do
    write "$iosched/low_latency" "0"
    write "$iosched/quantum" "64"
    write "$iosched/slide_idle" "0"
    write "$iosched/group_idle" "1"
done

# Dev Stune Boost
# Fast Sensivity in Game
write /dev/stune/background/schedtune.boost "2"
write /dev/stune/foreground/schedtune.boost "2"
write /dev/stune/rt/schedtune.boost "2"
write /dev/stune/top-app/schedtune.boost "2"
write /dev/stune/schedtune.boost "2"
write /dev/stune/nnapi-hal/schedtune.boost "2"
write /dev/stune/nnapi-hal/schedtune.prefer_idle "0"
write /dev/stune/top-app/schedtune.prefer_idle "0"
write /dev/stune/background/schedtune.prefer_idle "0"
write /dev/stune/foreground/schedtune.prefer_idle "0"
write /dev/stune/rt/schedtune.prefer_idle "0"
write /dev/stune/schedtune.prefer_idle "0"

# Fs
write /proc/sys/fs/lease-break-time "15"
write /proc/sys/fs/dir-notify-enable "0"
write /proc/sys/kernel/sched_migration_cost_ns "800000"
write /proc/sys/kernel/perf_cpu_time_max_percent "15"
write /proc/sys/kernel/sched_min_task_util_for_colocation "0"
write /proc/sys/kernel/sched_min_task_util_for_boost "0"
write /proc/sys/kernel/sched_min_granularity_ns "9000000"
write /proc/sys/kernel/sched_wakeup_granularity_ns "10000000"
write /proc/sys/kernel/sched_rt_runtime_us "955000"
write /proc/sys/kernel/sched_child_runs_first "0"
write /proc/sys/kernel/sched_boost_top_app "1"
write /proc/sys/kernel/sched_walt_rotate_big_tasks "1"
write /proc/sys/kernel/timer_migration "0"
write /proc/sys/kernel/sched_boost "1"
write /proc/sys/kernel/sched_nr_migrate "16"
write /proc/sys/kernel/sched_schedstats "0"
write /proc/sys/net/ipv4/tcp_fastopen "3"
write /proc/sys/vm/page-cluster "0"
write /proc/sys/net/ipv4/tcp_timestamps "0"
write /proc/sys/kernel/sched_rt_period_us "900000"

# Boost Control Tweak
# Credits to @Ratoriku
write /sys/module/boost_control/parameters/app_launch_boost_ms
"2500"

# Scheduler features
write /sys/kernel/debug/sched_features "NEXT_BUDDY"
write /sys/kernel/debug/sched_features "TTWU_QUEUE"
write /sys/kernel/debug/sched_features "NO_WAKEUP_PREEMPTION"
write /sys/kernel/debug/sched_features "NO_GENTLE_FAIR_SLEEPERS"
write /sys/kernel/debug/sched_features "STUNE_BOOST_BIAS_BIG"
write /sys/kernel/debug/sched_features "CACHE_HOT_BUDDY"
write /sys/kernel/debug/sched_features "LAST_BUDDY"
write /sys/kernel/debug/sched_features "SCHEDTUNE_BOOST_HOLD_ALL"
write /sys/kernel/debug/sched_features "SUGOV_RT_MAX_FREQ"

for cpu in /sys/devices/system/cpu/*/sched_load_boost
do
    write "$cpu" "1"
done


for boost in /sys/devices/system/*/cpu_boost
do
    write "$boost/sched_boost_on_input" "1"
    write "$boost/sched_boost_on_powerkey_input" "1"
    write "$boost/input_boost_ms" "130"
    write "$boost/powerkey_input_boost_ms" "450"
done