#!/system/bin/sh
# ZeetaaTweak V1
# by NotZeetaa

# Log path
LOG_FILE="/data/data/com.zeetaa.zeetaatweaks/files/log/main_log"

if [ -e $LOG_FILE ]; then
  rm -rf $LOG_FILE
fi

sendToLog() {
  timeZone=$(getprop persist.sys.timezone)
  printDate=$(TZ="$timeZone" date +"%H:%M:%S:%3N %d-%m-%Y")

  echo "[$printDate] $1" >>"$LOG_FILE"
}

write() {
  #chmod 0644 "$1"
  echo "$2" >"$1"

  currentValue=$(cat "$1")

  if [ "$currentValue" -eq "$2" ]; then
    sendToLog "$2 -✅-> $1"
  else
    sendToLog "$2 -⚠️-> $1"
  fi

  unset currentValue
}

write /sys/devices/system/cpu/cpu0/cpufreq/schedutil/down_rate_limit_us "0"
write /sys/devices/system/cpu/cpu1/cpufreq/schedutil/down_rate_limit_us "0"
write /sys/devices/system/cpu/cpu2/cpufreq/schedutil/down_rate_limit_us "0"
write /sys/devices/system/cpu/cpu3/cpufreq/schedutil/down_rate_limit_us "0"
write /sys/devices/system/cpu/cpu4/cpufreq/schedutil/down_rate_limit_us "0"
write /sys/devices/system/cpu/cpu5/cpufreq/schedutil/down_rate_limit_us "0"
write /sys/devices/system/cpu/cpu6/cpufreq/schedutil/down_rate_limit_us "0"
write /sys/devices/system/cpu/cpu7/cpufreq/schedutil/down_rate_limit_us "0"

write /sys/devices/system/cpu/cpu0/cpufreq/schedutil/up_rate_limit_us "2000"
write /sys/devices/system/cpu/cpu1/cpufreq/schedutil/up_rate_limit_us "2000"
write /sys/devices/system/cpu/cpu2/cpufreq/schedutil/up_rate_limit_us "2000"
write /sys/devices/system/cpu/cpu3/cpufreq/schedutil/up_rate_limit_us "2000"
write /sys/devices/system/cpu/cpu4/cpufreq/schedutil/up_rate_limit_us "2000"
write /sys/devices/system/cpu/cpu5/cpufreq/schedutil/up_rate_limit_us "2000"
write /sys/devices/system/cpu/cpu6/cpufreq/schedutil/up_rate_limit_us "2000"
write /sys/devices/system/cpu/cpu7/cpufreq/schedutil/up_rate_limit_us "2000"
write /sys/devices/system/cpu/cpu0/cpufreq/schedutil/iowait_boost_enable "0"
write /sys/devices/system/cpu/cpu1/cpufreq/schedutil/iowait_boost_enable "0"
write /sys/devices/system/cpu/cpu2/cpufreq/schedutil/iowait_boost_enable "0"
write /sys/devices/system/cpu/cpu3/cpufreq/schedutil/iowait_boost_enable "0"
write /sys/devices/system/cpu/cpu4/cpufreq/schedutil/iowait_boost_enable "0"
write /sys/devices/system/cpu/cpu5/cpufreq/schedutil/iowait_boost_enable "0"
write /sys/devices/system/cpu/cpu6/cpufreq/schedutil/iowait_boost_enable "0"
write /sys/devices/system/cpu/cpu7/cpufreq/schedutil/iowait_boost_enable "0"
write /sys/devices/system/cpu/cpu0/cpufreq/interactive/timer_slack "4"
write /sys/devices/system/cpu/cpu1/cpufreq/interactive/timer_slack "4"
write /sys/devices/system/cpu/cpu2/cpufreq/interactive/timer_slack "4"
write /sys/devices/system/cpu/cpu3/cpufreq/interactive/timer_slack "4"
write /sys/devices/system/cpu/cpu4/cpufreq/interactive/timer_slack "4"
write /sys/devices/system/cpu/cpu5/cpufreq/interactive/timer_slack "4"
write /sys/devices/system/cpu/cpu6/cpufreq/interactive/timer_slack "4"
write /sys/devices/system/cpu/cpu7/cpufreq/interactive/timer_slack "4"

for pro in /sys/devices/system/cpu/cpu*/cpufreq/interactive_pro/
do
    write "$pro/timer_slack" "4000"
done

# Gpu Tweaks
write /sys/class/kgsl/kgsl-3d0/throttling "1"
write /sys/class/kgsl/kgsl-3d0/default_pwrlevel "4"
write /sys/class/kgsl/kgsl-3d0/bus_split "1"

# Scheduler tweak

for sched in /sys/block/*/queue
do
    write "$sched/scheduler" "cfq"
    write "$sched/rq_affinity" "1"
    write "$sched/iostats" "0"
    write "$sched/read_ahead_kb" "128"
done

# Dev Stune Boost
# Fast Sensivity in Game
write /dev/stune/background/schedtune.boost "0"
write /dev/stune/foreground/schedtune.boost "0"
write /dev/stune/rt/schedtune.boost "0"
write /dev/stune/top-app/schedtune.boost "0"
write /dev/stune/schedtune.boost "0"
write /dev/stune/nnapi-hal/schedtune.boost "0"
write /dev/stune/nnapi-hal/schedtune.prefer_idle "1"
write /dev/stune/top-app/schedtune.prefer_idle "1"
write /dev/stune/background/schedtune.prefer_idle "1"
write /dev/stune/foreground/schedtune.prefer_idle "1"
write /dev/stune/rt/schedtune.prefer_idle "1"
write /dev/stune/schedtune.prefer_idle "1"

# Fs
write /proc/sys/fs/lease-break-time "15"
write /proc/sys/fs/dir-notify-enable "1"
write /proc/sys/kernel/perf_cpu_time_max_percent "25"
write /proc/sys/kernel/sched_min_task_util_for_colocation "100"
write /proc/sys/kernel/sched_min_task_util_for_boost "100"
write /proc/sys/kernel/sched_child_runs_first "0"
write /proc/sys/kernel/sched_boost_top_app "0"
write /proc/sys/kernel/sched_walt_rotate_big_tasks "0"
write /proc/sys/kernel/timer_migration "1"
write /proc/sys/kernel/sched_boost "0"
write /proc/sys/kernel/sched_nr_migrate "64"

# Boost Control Tweak
# Credits to @Ratoriku
write /sys/module/boost_control/parameters/app_launch_boost_ms
"0"

# Scheduler features
write /sys/kernel/debug/sched_features "NEXT_BUDDY"
write /sys/kernel/debug/sched_features "NO_TTWU_QUEUE"
write /sys/kernel/debug/sched_features "NO_WAKEUP_PREEMPTION"
write /sys/kernel/debug/sched_features "NO_GENTLE_FAIR_SLEEPERS"
write /sys/kernel/debug/sched_features "NO_STUNE_BOOST_BIAS_BIG"
write /sys/kernel/debug/sched_features "NO_CACHE_HOT_BUDDY"
write /sys/kernel/debug/sched_features "NO_LAST_BUDDY"

for cpu in /sys/devices/system/cpu/*/sched_load_boost
do
    write "$cpu" "0"
done


for boost in /sys/devices/system/*/cpu_boost
do
    write "$boost/sched_boost_on_input" "0"
    write "$boost/sched_boost_on_powerkey_input" "0"
    write "$boost/input_boost_ms" "0"
    write "$boost/powerkey_input_boost_ms" "0"
done